"""added task tracker

Revision ID: 1d5349e37ced
Revises: efc3b5068a72
Create Date: 2018-08-01 16:07:26.561995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5349e37ced'
down_revision = 'efc3b5068a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_task_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('block_number', sa.Numeric(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('logs', 'address',
               existing_type=sa.VARCHAR(length=42),
               nullable=False)
    op.alter_column('state_diff', 'address',
               existing_type=sa.VARCHAR(length=42),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('state_diff', 'address',
               existing_type=sa.VARCHAR(length=42),
               nullable=True)
    op.alter_column('logs', 'address',
               existing_type=sa.VARCHAR(length=42),
               nullable=True)
    op.drop_table('block_task_meta')
    # ### end Alembic commands ###
