"""added meta info table

Revision ID: 4722e540ad36
Revises: 10f48d555d4a
Create Date: 2018-06-14 14:36:38.287947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4722e540ad36'
down_revision = '10f48d555d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_pushed_block', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['last_pushed_block'], ['blocks.block_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_info')
    # ### end Alembic commands ###
